### ISSUE TITLE
🗂 Modify and Create Studies

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#113]
As a DRC admin or data-wrangler, I would like to directly create studies or modify existing details such as name and short name directly from the data tracker ui. This would more easily allow me to tweak information about my study.

- [x] #394 -> #403 - New study form view
- [x] #396 -> #429 - Link Cavatica projects to studies
- [x] #395 + #408 -> #420 - Study summary view
- [x] #411 -> #412 - Cavatica project admin view
- [x] #417 -> #426 - New analysis project for a study
- [x] #418 -> #424 - Modify existing study's details
