### ISSUE TITLE
📂 File Discovery

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#170]
As an internal user or administrator, I would like to search a study's files based on their description, type, and creation/modification date so that I may more easily find the file that I am searching for.

- [x] Descriptions available in file list (#169)
- [x] File list is sortable (#103)
- [x] File list is filterable (#180)
- [x] File list is paginated (#104)
- [x] File is searchable by file name and/or description (#181)
