### ISSUE TITLE
✨ File Versions

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#171]
As a data contributor, I would like to upload new versions of a file and download previous versions so that the file listing for my study only lists the most current data files.

- [x] #47 Add view for a single file
- [x] #219 Design mockup for file versions
- [x] kids-first/kf-api-study-creator#155 Support uploading new file versions
- [x] #177 Allow uploading of new versions for a file via file's page
- [x] #176 Display and allow download of old versions, including date when those versions were created
