### ISSUE TITLE
🎨 Update with new UI Kit components

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#184]
As a developer, I'd like to use the latest version of the UI Kit so as to re-use as many common components as possible and stay up to date with the design standards of Kids First.

- [x] #182 Upgrade UI Kit version -> #201 
- [x] #166 Replace secondary nav with UI Kit version
- [x] #165 Replace grid with UI Kit version
- [ ] #183 Replace badges with UI Kit version

**Comment by dankolbman** [comment]
Badges will need to be held off as they are blocked on brand and design standards.
