### ISSUE TITLE
♻️ Refactor for new design

### ISSUE THREAD

**Issue by XuTheBunny** [kids-first/kf-ui-data-tracker#271]
**Design:**

https://projects.invisionapp.com/share/2RQP4OEUAS3#/screens

**Tasks:**
- [x] #263 Refactor file annotation view
- [x] #266 Refactor version list component 
- [x] #267 Refactor file annotation modal
- [x] #268 Refactor version upload modal
- [x] #269 Add version detail modal
- [x] #270 Add version annotation modal
- [x] #277 Replace hard-coded badge component 
- [x] #278 Replace hard-coded avatar component 
- [x] #287 Add approval status dropdown to file annotation modal 
- [x] #291 Add notification bar on top of file list
- [x] #293 Add profile dropdown to header
