### ISSUE TITLE
💄 Replace UI Kit with semantic UI

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#307]
In order to better standardize interactions and design across apps, we will update our interfaces to use [Semantic UI](https://react.semantic-ui.com/) starting with the base style and component library with the ability to fork and extend later.

- [x] #300 -> #308  - Login View
- [x] #301 -> #336 - Study List View
- [x] #302 -> #318 - Study File List View
- [x] #303 -> #340 - File Detail View
- [x] #331 -> #333 - File Detail modals
- [x] #304 -> #350 New File View
- [x] #305 -> #315 - Profile View
- [x] #306 -> #309 - Token View
- [x] #319 -> #332 - Study Header
- [x] #320 -> #323 Nav Bar
