### ISSUE TITLE
📷 Improve Snapshot Coverage

### ISSUE THREAD

**Issue by XuTheBunny** [kids-first/kf-ui-data-tracker#494]
## Improvement:
- Each component has a description and the proptypes check
- Each component has as least one snapshot test in its default look
- Add more snapshot test with variations of the component look
- Each component has a check or a test for no data case
- Each component has the test file in `__test__` folder
- Refactor the component code when necessary
- Remove obsolete or duplicate components

## Snapshot Test Full Checklist

📁 AvatarTimeAgo: 
- [x] Look1: Show username and time ago
- [x] Look2: Hide username just show time ago
- [x] No data: No creator or no createAt data

📁 Badge:
- [x] Look1: Badge in all sizes and states
- [x] Look2: Badge in the filled/outlined color
- [x] No data: Missing state or not in default enum list

📁 CavaticaProjectList:
- [x] Look1: Toggle disableLink and hideStudy
- [x] Look2: Show hide edit button and unlink button
- [x] No data: Empty project list
- [x] Sort filter: Sort by name (should by createdAt)
- [x] Description: Add component description
- [x] Proptypes: Add proptypes for project list

📁 CopyButton:
- [x] Look: Style props and content pass to the button
- [x] No data: Text prop set to required
- [x] Functional: Check if the text is on the clipboard by the library
- [x] Folder: Put test file in test folder
- [x] Proptypes: Add proptypes for copy button

📁 EventList:
- [x] Look: Render event list using mock data
- [x] No data: Empty event list
- [x] Description: Add component description
- [x] Proptypes: Add proptypes for event list

📁 FileActionButtons:
- [x] Look1: Buttons in default, vertical or fluid
- [x] Look2: Buttons on loading stage
- [x] No data: Node prop set to required (file node)
- [x] Folder: Put test file in test folder
- [x] Refactor: Fix invalid props for button component

📁 FileAnnotation/SelectElement:
- [x] Remove: Remove obsolete component

📁 FileDetail/SelectElement:
- [x] Look: Element in selected or unselected stage with the full page
- [x] Proptypes: Update proptypes for select element

📁 FileDetail-EditExistingFile:
- [x] Refactor: Wrap fire events into act function

📁 FileList:
- [x] Look: File list element in normal and loading stage
- [x] No data: Missing study id for empty file list
- [x] Functional: Check if the files are sorted or filtered

📁 FileUploadTarget:
- [x] Look: Element with error, instructions or default
- [x] Bug: prop destructured not match the proptypes
- [x] Folder: Put test file in test folder

📁 Header:
- [x] Look1: Header for admin (in file editing test) or regular user
- [x] Look2: Header on loading stage
- [x] Refactor: Passing user data from view
- [x] No data: Missing user data (handled within component)

📁 ListFilterBar:
- [x] Look: ListFilterBar component in default look
- [x] No data: Missing file list data
- [x] Folder: Put test file in test folder

📁 StudyHeader:
- [x] Look1: Study header with or without the short name
- [x] Look2: Study header on the loading stage
- [x] No data: Missing study name
- [x] Refactor: conditional rendering short name
- [x] Folder: Put test file in the test folder

📁 StudyInfo/CavaticaCounts:
- [x] Look: Render cavatica counts using mock data
- [x] No data: Empty cavatica list
- [x] Folder: Put test file in test folder
- [x] Description: Add component description
- [x] Proptypes: Add proptypes for cavatica counts

📁 StudyInfo/FileCounts:
- [x] Look: Render file counts using mock data
- [x] No data: Empty files list
- [x] Folder: Put test file in test folder
- [x] Description: Add component description
- [x] Proptypes: Add proptypes for file counts

📁 StudyInfo/FileSimpleList:
- [x] Remove: Remove obsolete component

📁 StudyInfo/ProgressBar:
- [x] Look1: Render progress bar in three color stage
- [x] Look2: Render progress bar in error stage
- [x] No data: No values given to progress bar
- [x] Folder: Put test file in test folder

📁 StudyList:
- [x] Look1: Study list in. grid view and table view
- [x] Look2: Study list on the loading stage
- [x] Look3 Study list for admin or regular user
- [x] Refactor: Not render more than 16 columns
- [x] No data: Empty study list

📁 StudyNavBar:
- [x] Look: Render nav bar in default and beta look
- [x] Refactor: Add proptypes and mark required props

📁 ToggleButtons:
- [x] Look1: Render differents buttons as toggle buttons
- [x] Look2: Render the buttons in different sizes
- [x] Look3: Render the buttons with or without text
- [x] Description: Add component description

📁 TokenList:
- [x] Look: Token list with or without copy button
- [x] No data: Empty token list
- [x] Folder: Put test file in the test folder
- [x] Description: Add component description
- [x] Proptypes: Add proptypes for token list

📁 VersionList:
- [x] Look1: Render version list with mock data
- [x] Look2: Render version item with or without label
- [x] Refactor: Add table component outside version item
