### ISSUE TITLE
Create Research Studies UI

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#585]
We will begin adding a new 'Research Study' concept by adding a mockup UI which will only be visibly complete (no backend work) to evaluate the flow of creating and managing research studies.

- [x] #586 Create Research Studies view
- [x] #587 Split new study form
- [x] #592 Create new research study form

**Comment by dankolbman** [comment]
Not going to pursue this near term.
